/**
 * lib/cpfSubmissionExport.ts
 *
 * CPF e-Submit file generator for Singapore payroll.
 *
 * What this module does:
 * Generates the CPF e-Submit CSV file for monthly electronic submission to CPF Board.
 * The output is a UTF-8 CSV file with one header row and one data row per employee.
 *
 * CPF e-Submit format (from skills/sg-payroll-cpf/SKILL.md):
 *   Columns: NRIC/FIN, Employee Name, OW, AW, Employee CPF, Employer CPF
 *   - All amounts formatted to 2 decimal places
 *   - Submission deadline: 14th of the following month
 *
 * The file is returned as a Node.js Buffer containing the UTF-8 CSV bytes,
 * ready to be served as a file download with Content-Type: text/csv.
 *
 * Called by: app/api/payroll/export-cpf/route.ts
 */

import { type Payslip, type Employee } from "./schemas";

// ── Entity shape (only what the header comment needs) ─────────────────────────
type EntityForExport = {
  name: string;
  uen: string;
};

/**
 * Generates a CPF e-Submit CSV file for a payroll run.
 *
 * Columns per employee row:
 *   NRIC/FIN, Employee Name, OW, AW, Employee CPF, Employer CPF
 *
 * All amounts are formatted to 2 decimal places.
 * Employees without a stored NRIC/FIN will have that field left blank.
 *
 * @param payslips  - All payslips for this payroll run
 * @param employees - Employee records for this entity (used to look up NRIC/FIN and name)
 * @param entity    - Company info (name, UEN) included as a comment in the file header
 * @returns Buffer — UTF-8 CSV file ready for download
 */
export function generateCPFSubmission(
  payslips: Payslip[],
  employees: Employee[],
  entity: EntityForExport
): Buffer {
  // Build an employee lookup map for efficient access
  const employeeMap = new Map<string, Employee>();
  for (const emp of employees) {
    if (emp.id) {
      employeeMap.set(emp.id, emp);
    }
  }

  const lines: string[] = [];

  // ── File header comment (not part of the CPF e-Submit spec; for human reference) ─
  // The CPF e-Submit portal typically strips leading comment rows,
  // but including them aids auditing and manual review.
  lines.push(`# CPF e-Submit File`);
  lines.push(`# Employer: ${entity.name} (UEN: ${entity.uen})`);
  lines.push(`# Generated by FinAgent-SG`);
  lines.push(`# Submission deadline: 14th of the following month`);
  lines.push(`#`);

  // ── Column header row ────────────────────────────────────────────────────────
  lines.push(csvRow([
    "NRIC/FIN",
    "Employee Name",
    "Ordinary Wages (OW)",
    "Additional Wages (AW)",
    "Employee CPF",
    "Employer CPF",
  ]));

  // ── One data row per payslip ─────────────────────────────────────────────────
  for (const slip of payslips) {
    const emp = employeeMap.get(slip.employee_id);

    const nricFin = emp?.nric_fin ?? "";
    const empName = emp?.name ?? slip.employee_id;

    lines.push(csvRow([
      nricFin,
      empName,
      fmtAmount(slip.ordinary_wages),
      fmtAmount(slip.additional_wages),
      fmtAmount(slip.employee_cpf),
      fmtAmount(slip.employer_cpf),
    ]));
  }

  // Trailing newline per CSV convention
  lines.push("");

  return Buffer.from(lines.join("\n"), "utf-8");
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Formats a number to exactly 2 decimal places, no thousand separators.
 * Used for CPF e-Submit amounts (the portal expects plain numerics).
 */
function fmtAmount(value: number): string {
  return value.toFixed(2);
}

/**
 * Encodes a row of values as a CSV line.
 * Wraps any field containing a comma, double-quote, or newline in double quotes,
 * and escapes internal double-quotes by doubling them.
 */
function csvRow(fields: string[]): string {
  return fields
    .map((f) => {
      const needsQuoting = f.includes(",") || f.includes('"') || f.includes("\n");
      if (needsQuoting) {
        return `"${f.replace(/"/g, '""')}"`;
      }
      return f;
    })
    .join(",");
}
