/**
 * lib/outputStorage.ts
 *
 * Supabase persistence layer for FinAgent-SG generated outputs.
 *
 * What this module does:
 * Provides two functions for saving and retrieving generated financial statement
 * outputs from the client's Supabase schema:
 *
 * - saveGeneratedFS(): Inserts a completed FS generation record into the
 *   `outputs` table in the client's schema. Stores structured FS data,
 *   classified accounts, exemption result, and PDF binary (base64).
 *
 * - getLatestFS(): Retrieves the most recent financial_statements output for
 *   a given client schema. Used by Phase 3 to auto-load the base FS data
 *   for financial model projections.
 *
 * Multi-tenant pattern:
 * Each client has its own Supabase schema (e.g. "techsoft_pte_ltd").
 * Queries use `schema` option to target the correct client schema.
 * Schema names are generated by generateSchemaName() from lib/schemaUtils.ts.
 *
 * PDF storage:
 * The PDF binary is stored as a base64 TEXT string in the `pdf_data` column.
 * This will be migrated to Vercel Blob in a future phase.
 */

import { supabase } from "./supabaseClient";
import { type FSOutput, type ClassifiedAccount, type ExemptionResult } from "./schemas";

export type SaveGeneratedFSParams = {
  schemaName: string;           // Client schema name, e.g. "techsoft_pte_ltd"
  fiscalYearId: string;         // UUID of the fiscal_years row
  fsOutput: FSOutput;           // Full structured FS output from fsGenerator.ts
  classifiedAccounts: ClassifiedAccount[];  // Classified trial balance lines
  exemptionResult: ExemptionResult;         // Audit exemption determination
  pdfBase64: string | null;     // Base64-encoded PDF binary, or null if not yet generated
};

export type SavedFSRecord = {
  id: string;
  fiscal_year_id: string;
  output_type: string;
  structured_data: FSOutput;
  classified_accounts: ClassifiedAccount[];
  exemption_result: ExemptionResult;
  pdf_data: string | null;
  created_at: string;
};

/**
 * Saves a completed FS generation to the client's Supabase `outputs` table.
 *
 * @returns The inserted row's id, or throws on error.
 */
export async function saveGeneratedFS(params: SaveGeneratedFSParams): Promise<string> {
  const {
    schemaName,
    fiscalYearId,
    fsOutput,
    classifiedAccounts,
    exemptionResult,
    pdfBase64,
  } = params;

  const { data, error } = await supabase
    .schema(schemaName)
    .from("outputs")
    .insert({
      fiscal_year_id: fiscalYearId,
      output_type: "financial_statements",
      structured_data: fsOutput,
      classified_accounts: classifiedAccounts,
      exemption_result: exemptionResult,
      pdf_data: pdfBase64,
    })
    .select("id")
    .single();

  if (error) {
    throw new Error(`Failed to save FS output to Supabase: ${error.message}`);
  }

  return data.id as string;
}

/**
 * Retrieves the most recent financial_statements output for a client schema.
 * Returns null if no outputs exist yet.
 *
 * Used by Phase 3 to auto-load the latest FS as the base for financial projections.
 *
 * @param schemaName - Client schema name, e.g. "techsoft_pte_ltd"
 * @param fiscalYearId - Optional UUID to filter by specific fiscal year
 */
export async function getLatestFS(
  schemaName: string,
  fiscalYearId?: string
): Promise<SavedFSRecord | null> {
  let query = supabase
    .schema(schemaName)
    .from("outputs")
    .select("*")
    .eq("output_type", "financial_statements")
    .order("created_at", { ascending: false })
    .limit(1);

  if (fiscalYearId) {
    query = query.eq("fiscal_year_id", fiscalYearId);
  }

  const { data, error } = await query.single();

  if (error) {
    // PGRST116 = no rows returned — not an error condition
    if (error.code === "PGRST116") return null;
    throw new Error(`Failed to retrieve FS output from Supabase: ${error.message}`);
  }

  return data as SavedFSRecord;
}
